version: '3.8'

services:
  db:
    image: postgres:16
    container_name: paidazikadb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: paidazikadb
    volumes:
      - paidazikadb_data:/var/lib/postgresql/data
    networks:
      - paidazika-network

volumes:
  paidazikadb_data:

networks:
  paidazika-network:
